### ISSUE TITLE
Process dies silently on error (node 10 / VS 2017)

### ISSUE THREAD

**Issue by simonbuchan** [mmraff/windows-users#2]
When running `require('windows-users').getDetails('NoSuchUser')` I don't get the expected JS error / no result, instead the process simply silently exits with exit code `-1073740940`, which looks like an unhandled SEH exception? `getDetails('simon')` works, as does `list()`.

Looking at the code, I'm not sure what's up here, `throw new Snag()` / `catch (Snag*)` should work, even if throwing pointers gives me wiggles 🙀

It's possible this is because I'm running on Node 10, which requires updating `nan` due to the removal of `v8::Object::ForceSet()` (`Nan::ForceSet()` remains, as a deprecated wrapper for `Nan::DefineObjectProperty()` with slightly different semantics).

**Comment by mmraff** [comment]
Hi Simon,

Glad to hear from you.

When I last tested windows-users, it was with Node 6, and on Windows 7.
I will look into this ASAP.

Thanks!
